# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0003_battlevaluestructure_itemflow_moneyflow_playerfeaturesflow_playerlevelup_playerlogin_playerlogout_pl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventtimes',
            fields=[
                ('id', models.BigIntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('izoneareaid', models.IntegerField(db_column='iZoneAreaID')),
                ('dteventtime', models.DateTimeField(db_column='dtEventTime')),
                ('sequence', models.IntegerField(blank=True, db_column='Sequence', null=True)),
                ('vgameappid', models.CharField(blank=True, db_column='vGameAppid', max_length=32, null=True)),
                ('platid', models.IntegerField(db_column='PlatID')),
                ('dvid', models.CharField(blank=True, db_column='DVID', max_length=64, null=True)),
                ('level', models.IntegerField(blank=True, db_column='Level', null=True)),
                ('type', models.IntegerField(blank=True, db_column='Type', null=True)),
                ('times', models.IntegerField(blank=True, db_column='Times', null=True)),
                ('nickname', models.CharField(blank=True, db_column='Nickname', max_length=64, null=True)),
                ('uid', models.BigIntegerField(blank=True, db_column='UID', null=True)),
                ('tarname', models.CharField(blank=True, db_column='TarName', max_length=32, null=True)),
                ('tartype', models.IntegerField(blank=True, db_column='TarType', null=True)),
                ('tarlevel', models.IntegerField(blank=True, db_column='TarLevel', null=True)),
                ('atkway', models.IntegerField(blank=True, db_column='AtkWay', null=True)),
                ('originallevel', models.IntegerField(blank=True, db_column='OriginalLevel', null=True)),
                ('color', models.IntegerField(blank=True, db_column='Color', null=True)),
                ('opttype', models.IntegerField(blank=True, db_column='Opttype', null=True)),
                ('num', models.IntegerField(blank=True, db_column='Num', null=True)),
                ('winning', models.IntegerField(blank=True, db_column='Winning', null=True)),
                ('defresult', models.IntegerField(blank=True, db_column='Defresult', null=True)),
                ('tarcatslelevel', models.IntegerField(blank=True, db_column='TarCatsleLevel', null=True)),
                ('fbid', models.CharField(blank=True, db_column='FBID', max_length=64, null=True)),
                ('apid', models.CharField(blank=True, db_column='APID', max_length=64, null=True)),
                ('hurtendtime', models.CharField(blank=True, db_column='HurtEndTime', max_length=64, null=True)),
                ('numtwo', models.IntegerField(blank=True, db_column='NumTwo', null=True)),
            ],
            options={
                'db_table': 'EventTimes',
                'managed': False,
            },
        ),
    ]
