# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0005_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('views_playerManage', '查看玩家管理'),), 'verbose_name': '权限表', 'verbose_name_plural': '权限表'},
        ),
    ]
