# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0008_auto_20171031_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('views_get_slg_users_tem', '查看玩家管理'), ('views_get_slg_alliance_tem', '查看联盟管理'), ('views_get_slg_mail_notice_tem', '查看公告邮件'), ('views_get_slg_order_tem', '查看订单系统'), ('views_get_slg_reward_tem', '查看礼包奖励'), ('views_get_slg_service_reply_tem', '查看客服反馈'), ('views_get_slg_user_log_tem', '查看玩家日志'), ('views_get_slg_server_tem', '查看服务器管理'), ('views_get_slg_manager_tem', '查看管理员管理')), 'verbose_name': '权限表', 'verbose_name_plural': '权限表'},
        ),
    ]
