# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0009_auto_20171101_0328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
