# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0010_delete_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'slg_permission',
                'permissions': (('views_slg_users_tem', '查看玩家管理'), ('views_slg_alliance_tem', '查看联盟管理'), ('views_slg_mail_notice_tem', '查看公告邮件'), ('views_slg_order_tem', '查看订单系统'), ('views_slg_reward_tem', '查看礼包奖励'), ('views_slg_service_reply_tem', '查看客服反馈'), ('views_slg_user_log_tem', '查看玩家日志'), ('views_slg_server_tem', '查看服务器管理'), ('views_slg_manager_tem', '查看管理员管理')),
            },
        ),
    ]
