# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slg', '0011_permission'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table=None,
        ),
    ]
